### PR TITLE
Feature/make filters more flexible

### PR DESCRIPTION
**Pull request by cwdt**

### CODE REVIEW

**Comment by blackvault-bv** [comment]
Looks good 👍

Can you move the Doctrine builder and Filters to its own namespace (move the builder to the namespace and extend the current one for BC with deprecation comment on the class). e.g. OneMustCode\Query\Builders\Doctrine. This because there will be an Eloquent Builder in the future.

And some documentation on how to register custom filters for doctrine.

When typing this you already changed the FilterHandler to FilterHandlerInterface, thats good :)

**Comment by cwdt** [comment]
Like this? It's untested yet. I will test it if the code looks okay!

**Comment by blackvault-bv** [comment]
Yeah, that's exactly what i had in mind 👍

**Comment by cwdt** [comment]
Looks like it's working!

**Pull request merged**
